# this is GIthub actions to help compare Azure DevOps YAML

name: Comparing with Azure Pipeline

#  trigger:
#   - conflict
on:
  push:
    branches:
      - conflict 

# # pool:
#    vmImage: ubuntu-latest

jobs:
   first:
     runs-on: ubuntu-latest

     steps:
     - name: One-line
       run: echo Hello, World !!!

     - name: Multi-Line
       run: |
         echo Add other tasks to build, test, and deploy your project.
         echo This is AJ !!!
  
